import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { auth } from "@/auth";
import InactivityAutoLogout from "@/components/InactivityAutoLogout";
import { RealtimeProvider } from "@/lib/realtime/RealtimeContext";
import NotificationToast from "@/components/realtime/NotificationToast";

// console.log("AUTH_SECRET:", process.env.AUTH_SECRET);
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kitchen Flow System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isLoggedIn = !!session?.user;
  const user = session?.user ? { role: session.user.role as any } : null;

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RealtimeProvider user={user}>
          {children} 
          <NotificationToast />
        </RealtimeProvider>
        <InactivityAutoLogout isLoggedIn={isLoggedIn} />
      </body>
    </html>
  );
}

