import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kitchen Flow System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        
        {children} 

        {/* <footer className="flex justify-center py-4 text-center text-xl font-bold bg-amber-950 h-16 w-full ">
          <p className="flex gap-4">
            &copy; {new Date().getFullYear()} Kitchen Flow System
          </p>
        </footer>  */}
      </body>
    </html>
  );
}
